//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniNetMobile.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlumniNetMobile.Resx.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a description.
        /// </summary>
        internal static string AddDescription {
            get {
                return ResourceManager.GetString("AddDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumni events.
        /// </summary>
        internal static string AlumniEvents {
            get {
                return ResourceManager.GetString("AlumniEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t update. One or more URLs are not passing the verification.
        /// </summary>
        internal static string CantUpdateUrlNotPassing {
            get {
                return ResourceManager.GetString("CantUpdateUrlNotPassing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change application language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your connection.
        /// </summary>
        internal static string CheckConnection {
            get {
                return ResourceManager.GetString("CheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        internal static string CompanyNamePlaceholder {
            get {
                return ResourceManager.GetString("CompanyNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create post.
        /// </summary>
        internal static string CreatePost {
            get {
                return ResourceManager.GetString("CreatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stergeti.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this finished study?.
        /// </summary>
        internal static string DeleteFinishedStudy {
            get {
                return ResourceManager.GetString("DeleteFinishedStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this job?.
        /// </summary>
        internal static string DeleteJob {
            get {
                return ResourceManager.GetString("DeleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account ? Sign up.
        /// </summary>
        internal static string DontHaveAnAccountSignUp {
            get {
                return ResourceManager.GetString("DontHaveAnAccountSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work experience.
        /// </summary>
        internal static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty name.
        /// </summary>
        internal static string FacultyName {
            get {
                return ResourceManager.GetString("FacultyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty not found.
        /// </summary>
        internal static string FacultyNotFound {
            get {
                return ResourceManager.GetString("FacultyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished studies.
        /// </summary>
        internal static string FinishedStudies {
            get {
                return ResourceManager.GetString("FinishedStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduation year.
        /// </summary>
        internal static string GraduationYear {
            get {
                return ResourceManager.GetString("GraduationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending year.
        /// </summary>
        internal static string JobEndYear {
            get {
                return ResourceManager.GetString("JobEndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting year.
        /// </summary>
        internal static string JobStartYear {
            get {
                return ResourceManager.GetString("JobStartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        internal static string JobTitlePlaceholder {
            get {
                return ResourceManager.GetString("JobTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection found!.
        /// </summary>
        internal static string NoInternetConnectionMessage {
            get {
                return ResourceManager.GetString("NoInternetConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no posts awaiting for a review.
        /// </summary>
        internal static string NoPostsForReview {
            get {
                return ResourceManager.GetString("NoPostsForReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent:.
        /// </summary>
        internal static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover your account.
        /// </summary>
        internal static string RecoverAccount {
            get {
                return ResourceManager.GetString("RecoverAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove picture.
        /// </summary>
        internal static string RemovePicture {
            get {
                return ResourceManager.GetString("RemovePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        internal static string Romanian {
            get {
                return ResourceManager.GetString("Romanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the education form.
        /// </summary>
        internal static string SelectLearningSchedule {
            get {
                return ResourceManager.GetString("SelectLearningSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option.
        /// </summary>
        internal static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a picture.
        /// </summary>
        internal static string SelectPicture {
            get {
                return ResourceManager.GetString("SelectPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a study program.
        /// </summary>
        internal static string SelectStudyProgram {
            get {
                return ResourceManager.GetString("SelectStudyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send recovery email.
        /// </summary>
        internal static string SendRecoveryEmail {
            get {
                return ResourceManager.GetString("SendRecoveryEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        internal static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization not found.
        /// </summary>
        internal static string SpecializationNotFound {
            get {
                return ResourceManager.GetString("SpecializationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still employed.
        /// </summary>
        internal static string StillEmployed {
            get {
                return ResourceManager.GetString("StillEmployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your preferences.
        /// </summary>
        internal static string YourPreferences {
            get {
                return ResourceManager.GetString("YourPreferences", resourceCulture);
            }
        }
    }
}
